ktor:
  application:
    modules:
      - com.koltsov.captain.calculator.items.service.ApplicationKt.module
  deployment:
    port: 8080

db:
  driver: org.postgresql.Driver
  url: "jdbc:postgresql://localhost:5432/items-service"
  username: items-service
  password: items-service
