ktor:
  application:
    modules:
      - com.koltsov.captain.calculator.items.service.ApplicationKt.module
  deployment:
    port: 8080

postgres:
  url: "jdbc:postgresql://localhost:5432/items-service"
  user: items-service
  password: items-service
